#!/usr/bin/env node

exports.unitList = {
    "animus": ["Animus", "10", "N", "6", "-", "2", "N", "N", "-", "N", "-", "-", "-", "-", "Gain RR", "-"],
    "blastforge": ["Blastforge", "10", "N", "5", "-", "3", "N", "N", "-", "N", "-", "-", "-", "-", "Gain B", "-"],
    "conduit": ["Conduit", "10", "N", "4", "-", "3", "Y", "N", "-", "N", "-", "-", "-", "-", "Gain G", "-"],
    "drone": ["Drone", "20", "N", "3E", "-", "1", "N", "Y", "N", "N", "-", "-", "-", "-", "-", "Gain 1"],
    "engineer": ["Engineer", "20", "N", "2", "-", "1", "N", "Y", "N", "N", "-", "-", "-", "-", "Gain E", "-"],
    "forcefield": ["Forcefield", "10", "N", "1G", "Consume Drone", "2", "Y", "Y", "Y", "N", "-", "-", "-", "-", "-", "-"],
    "gausscannon": ["Gauss Cannon", "10", "N", "6G", "-", "5", "Y", "N", "-", "N", "-", "-", "-", "-", "Gain X", "-"],
    "steelsplitter": ["Steelsplitter", "10", "N", "6B", "", "3", "N", "Y", "N", "N", "-", "-", "-", "-", "-", "Gain X"],
    "wall": ["Wall", "10", "N", "5B", "-", "3", "N", "Y", "Y", "N", "-", "-", "-", "-", "-", "-"],
    "tarsier": ["Tarsier", "10", "N", "4R", "-", "1", "N", "N", "-", "N", "2", "-", "-", "-", "Gain X", "-"],
    "rhino": ["Rhino", "10", "N", "5R", "-", "2", "N", "Y", "Y", "N", "-", "-", "2", "-", "-", "Gain X"],
    "steelforge": ["Steelforge", "4", "N", "2", "Consume Blastforge", "4", "N", "N", "-", "N", "-", "-", "-", "-", "Gain B", "Consume Drone to construct Steelsplitter"],
    "centrifuge": ["Centrifuge", "1", "N", "12EEE", "-", "1", "N", "N", "-", "N", "3", "-", "-", "-", "Gain 20GGBBRR, sacrifice this", "-"],
    "doomeddrone": ["Doomed Drone", "20", "N", "2E", "-", "1", "N", "Y", "N", "N", "-", "4", "-", "-", "-", "Gain 1"],
    "auricimpulse": ["Auric Impulse", "20", "N", "3E", "-", "1", "N", "N", "-", "N", "-", "-", "-", "-", "Gain 4, sacrifice this", "-"],
    "vividdrone": ["Vivid Drone", "4", "N", "4EEE", "Consume 3 Drones", "1", "N", "N", "-", "N", "-", "-", "-", "-", "Gain 5", "-"],
    "wilddrone": ["Wild Drone", "10", "N", "5EE", "-", "3", "N", "N", "-", "Y", "-", "-", "-", "-", "Gain 2", "-"],
    "aegis": ["Aegis", "10", "N", "6GGG", "-", "5", "Y", "Y", "Y", "N", "-", "-", "-", "-", "-", "-"],
    "cluster bolt": ["Cluster Bolt", "10", "Y", "GGGG", "-", "-", "-", "-", "-", "-", "-", "-", "-", "Construct 5 Gauss Charges, construct 2 Gauss Charges for opponent", "-", "-"],
    "cryoray": ["Cryo Ray", "10", "N", "1G", "-", "3", "Y", "N", "-", "N", "-", "-", "-", "-", "-", "Lose 1 health to Chill 1"],
    "gausscharge": ["Gauss Charge", "20", "N", "1G", "-", "1", "N", "N", "-", "N", "-", "-", "-", "-", "Gain X, sacrifice this", "-"],
    "defensegrid": ["Defense Grid", "1", "N", "16BBB", "-", "7", "N", "Y", "N", "N", "-", "7", "-", "-", "Construct Drone", "-"],
    "gaussfabricator": ["Gauss Fabricator", "1", "N", "13GGGG", "-", "13", "Y", "N", "-", "N", "-", "8", "-", "-", "Construct Gauss Cannon", "-"],
    "isokronus": ["Iso Kronus", "10", "N", "5G", "-", "5", "Y", "N", "-", "N", "2", "-", "-", "-", "Gain XX, Exhaust 2", "-"],
    "trinitydrone": ["Trinity Drone", "10", "N", "2EG", "Consume 2 Drones", "5", "Y", "N", "-", "N", "-", "-", "-", "-", "Gain 3", "-"],
    "vengecannon": ["Venge Cannon", "10", "N", "3GGG", "Consume 3 Drones", "8", "Y", "N", "-", "N", "-", "-", "-", "-", "Gain XX", "Lose 2 health, pay GGG to construct 3 Gauss Charges"],
    "doomedmech": ["Doomed Mech", "10", "N", "8BB", "-", "5", "N", "Y", "N", "N", "-", "5", "-", "-", "-", "Gain XX"],
    "doomedwall": ["Doomed Wall", "10", "N", "7B", "-", "4", "N", "Y", "Y", "N", "-", "3", "-", "-", "-", "-"],
    "drake": ["Drake", "4", "N", "16BBB", "-", "5", "N", "N", "-", "N", "-", "-", "-", "-", "Gain XXX", "Consume Blastforge to Gain XX"],
    "energymatrix": ["Energy Matrix", "4", "N", "9BB", "-", "5", "N", "Y", "Y", "N", "-", "-", "-", "Construct Pixie", "-", "-"],
    "flameanimus": ["Flame Animus", "4", "N", "7B", "-", "2", "N", "N", "-", "N", "-", "-", "-", "-", "Gain RX", "-"],
    "grenademech": ["Grenade Mech", "10", "N", "10BB", "-", "4", "N", "N", "-", "N", "-", "-", "-", "Construct 3 Pixies", "Gain X", "Consume Blastforge to construct 2 Pixies"],
    "militia": ["Militia", "10", "N", "6B", "-", "2", "N", "N", "N", "N", "-", "-", "-", "-", "Gain X", "Pay X to Gain 1"],
    "omegasplitter": ["Omega Splitter", "4", "N", "14BBB", "-", "6", "N", "Y", "N", "N", "-", "-", "-", "-", "-", "Gain XXX"],
    "pixie": ["Pixie", "20", "N", "1B", "-", "1", "N", "N", "-", "N", "-", "-", "-", "-", "-", "Sacrifice this to Gain X"],
    "polywall": ["Polywall", "10", "N", "10B", "-", "6", "N", "Y", "Y", "Y", "-", "-", "-", "-", "-", "-"],
    "shredder": ["Shredder", "10", "N", "5B", "-", "4", "N", "Y", "N", "Y", "-", "-", "-", "-", "-", "Gain X"],
    "amporilla": ["Amporilla", "4", "N", "12RRR", "-", "3", "N", "N", "-", "N", "-", "-", "-", "-", "Gain X for each ready Tarsier you have", "-"],
    "bloodrager": ["Bloodrager", "4", "N", "7RXXX", "-", "2", "N", "N", "-", "N", "-", "-", "-", "-", "Gain XX", "-"],
    "electrovore": ["Electrovore", "10", "N", "4R", "-", "2", "N", "Y", "N", "N", "-", "-", "-", "-", "-", "Pay E to gain X"],
    "frostbite": ["Frostbite", "20", "N", "2R", "-", "1", "N", "N", "-", "N", "-", "-", "-", "-", "-", "Sacrifice this to Chill 3"],
    "gaussite symbiote": ["Gaussite Symbiote", "4", "N", "7RR", "-", "2", "N", "N", "-", "N", "-", "-", "-", "-", "Gain GX", "Sacrifice this and pay GGG to construct 5 Gauss Charges"],
    "grimbotch": ["Grimbotch", "10", "N", "4R", "-", "2", "N", "Y", "N", "N", "-", "4", "-", "-", "-", "Gain X"],
    "husk": ["Husk", "20", "N", "2R", "-", "1", "N", "Y", "Y", "N", "-", "-", "-", "-", "-", "-"],
    "lucinaspinos": ["Lucina Spinos", "1", "N", "17RRRR", "-", "1", "N", "N", "-", "N", "-", "-", "-", "-", "Gain XXXX", "Consume Drone to construct Perforator"],
    "perforator": ["Perforator", "10", "N", "3R", "-", "2", "N", "Y", "N", "N", "-", "-", "-", "-", "-", "Pay R to Gain X"],
    "shadowfang": ["Shadowfang", "10", "N", "7RRR", "-", "1", "N", "N", "-", "N", "-", "-", "-", "-", "Gain XX", "-"],
    "shiveryeti": ["Shiver Yeti", "10", "N", "5R", "-", "2", "N", "Y", "Y", "N", "-", "-", "-", "-", "-", "Chill 2"],
    "tatsunullifier": ["Tatsu Nullifier", "4", "N", "11RRRR", "-", "2", "N", "N", "-", "N", "-", "-", "-", "-", "Gain XX", "Chill 5"],
    "antimacomet": ["Antima Comet", "1", "N", "3GBR", "-", "1", "N", "N", "-", "N", "2", "-", "-", "-", "Gain X for each Engineer you have, sacrifice this", "-"],
    "plasmafier": ["Plasmafier", "4", "N", "12GGGB", "-", "4", "Y", "Y", "N", "N", "-", "-", "-", "-", "-", "Consume Drone to Gain XXXX"],
    "teslacoil": ["Tesla Coil", "4", "N", "10GGB", "-", "3", "Y", "N", "-", "N", "-", "-", "-", "Construct 2 Engineers", "-", "Consume Engineer to Gain XXX"],
    "xenoguardian": ["Xeno Guardian", "10", "N", "7GB", "-", "4", "N", "Y", "N", "N", "-", "-", "-", "-", "Gain X", "-"],
    "feralwarden": ["Feral Warden", "10", "N", "5GR", "-", "3", "Y", "Y", "Y", "N", "-", "-", "-", "-", "-", "Gain X"],
    "protoplasm": ["Protoplasm", "10", "N", "7GGRR", "-", "4", "Y", "Y", "Y", "N", "-", "-", "-", "-", "-", "Sacrifice this to gain XXXX"],
    "scorchilla": ["Scorchilla", "10", "N", "5GR", "-", "3", "Y", "Y", "N", "N", "2", "-", "-", "-", "-", "Gain XXX, Exhaust 3"],
    "sentinel": ["Sentinel", "10", "N", "8GR", "-", "4", "Y", "Y", "N", "N", "-", "-", "4", "-", "-", "Gain X, construct Engineer"],
    "tiathurnax": ["Tia Thurnax", "1", "N", "6GGGR", "Consume 7 Drones", "4", "Y", "Y", "Y", "N", "-", "-", "3", "-", "-", "Gain XXXXXXX"],
    "cauterizer": ["Cauterizer", "4", "N", "11BRR", "-", "3", "N", "Y", "N", "N", "-", "-", "-", "Construct 4 Engineers", "-", "Pay EEEE to gain XX"],
    "hannibull": ["Hannibull", "4", "N", "9BR", "-", "6", "N", "Y", "N", "Y", "-", "-", "-", "-", "-", "Gain XX"],
    "icebladegolem": ["Iceblade Golem", "10", "N", "7BR", "-", "6", "N", "N", "-", "Y", "-", "-", "-", "-", "Gain X", "Chill 2"],
    "centurion": ["Centurion", "1", "N", "18GGBBR", "-", "6", "N", "Y", "Y", "N", "-", "-", "-", "-", "Gain XX", "-"],
    "apollo": ["Apollo", "1", "N", "13BBB", "-", "4", "N", "N", "-", "N", "2", "-", "-", "-", "-", "Destroy unit with 3 or less health"],
    "auridecore": ["Auride Core", "4", "N", "1B", "-", "1", "N", "N", "-", "N", "-", "-", "-", "-", "-", "Pay X to Gain 2"],
    "deadeyeoperative": ["Deadeye Operative", "4", "N", "4BB", "Consume Steelsplitter", "4", "N", "N", "-", "N", "-", "-", "-", "-", "Gain XX", "Pay XX to destroy non-blocking Drone"],
    "hellhound": ["Hellhound", "10", "N", "1BR", "-", "1", "N", "N", "-", "N", "-", "-", "-", "Construct Engineer", "Gain X", "-"],
    "odin": ["Odin", "1", "N", "21BBB", "-", "5", "N", "Y", "N", "N", "-", "-", "-", "Construct 3 Steelsplitters", "-", "Sacrifice Steelsplitter to gain XXXX"],
    "ossifieddrone": ["Ossified Drone", "1", "N", "2R", "Consume Drone", "2", "N", "Y", "N", "N", "-", "-", "-", "-", "Gain 1", "Pay R, consume Drone to Construct Ossified Drone"],
    "synthesizer": ["Synthesizer", "4", "N", "6B", "-", "4", "N", "N", "-", "N", "-", "-", "-", "-", "Gain GG", "Pay GGG to Gain BB"],
    "thermitecore": ["Thermite Core", "4", "N", "1B", "-", "1", "N", "N", "-", "N", "-", "7", "-", "-", "-", "Pay X to Construct Pixie"],
    "zemoravoidbringer": ["Zemora Voidbringer", "1", "N", "6GG", "-", "20", "Y", "N", "-", "N", "6", "-", "-", "-", "-", "Pay GGGGGGGG to gain 8XXXXXXXX"],
    "bloodpact": ["Blood Pact", "10", "Y", "3R", "-", "-", "-", "-", "-", "-", "-", "-", "-", "Construct 4 Prompt Husks; construct a 1-buildtime Tarsier for opponent", "-", "-"],
    "chronofilter": ["Chrono Filter", "1", "N", "4", "-", "2", "N", "N", "-", "N", "-", "-", "-", "-", "Gain BR, Exhaust 2", "-"],
    "astericannon": ["Asteri Cannon", "4", "N", "16GGGG", "-", "11", "Y", "N", "-", "N", "-", "-", "-", "-", "Gain XXX", "Lose 5 health to construct Prompt Forcefield"],
    "barrier": ["Barrier", "20", "N", "1G", "-", "1", "Y", "Y", "Y", "N", "-", "1", "-", "-", "-", "-"],
    "plexocell": ["Plexo Cell", "10", "N", "2GG", "Consume Drone", "4", "Y", "Y", "Y", "N", "-", "1", "-", "-", "-", "-"],
    "frostbrooder": ["Frost Brooder", "4", "N", "5RR", "-", "2", "N", "N", "-", "N", "-", "7", "-", "-", "Construct Frostbite", "-"],
    "chieftain": ["Chieftain", "10", "N", "7GGB", "-", "7", "Y", "Y", "N", "N", "-", "3", "-", "-", "-", "Gain XX"],
    "fissionturret": ["Fission Turret", "10", "N", "4G", "-", "1", "N", "N", "-", "N", "-", "4", "-", "-", "Gain X", "Pay EEEE and sacrifice this to gain GGGG"],
    "immolite": ["Immolite", "20", "N", "3R", "-", "1", "N", "Y", "N", "N", "-", "-", "-", "-", "-", "Gain X, Exhaust 2"],
    "cynestra": ["Cynestra", "4", "N", "11GGGR", "-", "2", "Y", "N", "-", "N", "-", "-", "-", "-", "Gain XXX", "-"],
    "endothermkit": ["Endotherm Kit", "1", "Y", "5GGRR", "-", "-", "-", "-", "-", "-", "-", "-", "-", "Construct 4 4-buildtime Frostbites, construct 4 4-buildtime Cryo Rays", "-", "-"],
    "infusiongrid": ["Infusion Grid", "10", "N", "5B", "-", "4", "N", "Y", "N", "N", "-", "-", "-", "-", "-", "Pay R , sacrifice this to construct 4 Prompt Husks"],
    "maharrectifier": ["Mahar Rectifier", "10", "N", "11GG", "-", "5", "Y", "Y", "N", "N", "-", "-", "-", "-", "-", "Gain XX"],
    "arkasodara": ["Arka Sodara", "1", "N", "7BBRXXXXXXX", "-", "7", "N", "Y", "Y", "N", "-", "-", "-", "-", "-", "Gain XXXX"],
    "redeemer": ["Redeemer", "4", "N", "8GGB", "-", "4", "N", "Y", "N", "N", "-", "-", "-", "Construct 4 Gauss Charges for opponent", "-", "Gain XXX"]
};
